name: rosie
favicon: null
layout_spectrum: 0.3873365072067827
typography_spectrum: 0.8980342852883041
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7281877966597676
  lightness: 0.28228295454755425
  saturation: 0.1654962955508381
  rhythmicContrast: 0.9233978819102049
purpose: []
